[
    {
		path: '/camp',
        meta: {
            disable: false,
            desc: '精英训练营',
            descEn: 'Elite Camp',
            key: 'camp',
            name: '精英训练营',
            type: 'menu',
            level: 0,
            hidden: false,
        },
        component: () => import('@/views/camp'),
        children: [
            {
                children: [
                    {
                        children: [],
                        path: '/camp/schedule/viewSchedule',
                        meta: {
                            disable: false,
                            desc: '训练营日程-详情',
                            descEn: 'Camp Schedule Detail',
                            key: 'camp-schedule-detail',
                            name: '训练营日程-详情',
                            type: 'menu',
                            level: 1,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/schedule/viewSchedule'),
                    },
                    {
                        children: [],
                        path: '/camp/schedule/addSchedule',
                        meta: {
                            disable: false,
                            desc: '训练营日程-添加/编辑',
                            descEn: 'Camp Schedule Edit',
                            key: 'camp-schedule-edit',
                            name: '训练营日程-添加/编辑',
                            type: 'menu',
                            level: 1,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/schedule/addSchedule'),
                    },
                    {
                        children: [],
                        path: '/camp/schedule/index',
                        meta: {
                            disable: false,
                            desc: '训练营日程-首页',
                            descEn: 'Camp Schedule Home',
                            key: 'camp-schedule-index',
                            name: '训练营日程-首页',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/schedule/index'),
                    },
                ],
                path: '/camp/schedule/index',
                meta: {
                    disable: false,
                    desc: '训练营日程',
                    descEn: 'Camp Sche.',
                    key: 'camp-schedule',
                    name: '训练营日程',
                    type: 'menu',
                    level: 1,
                    hidden: false,
                },
                component: () => import('@/views/camp/schedule/index'),
            },
            {
                children: [
                    {
                        children: [],
                        path: '/camp/team/index',
                        meta: {
                            disable: false,
                            desc: '训练营梯队列表页',
                            descEn: '训练营梯队列表页',
                            name: '训练营梯队列表页',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/team/index'),
                    },
                    {
                        children: [],
                        path: '/camp/team/details',
                        meta: {
                            disable: false,
                            desc: '训练营梯队人员详情页',
                            descEn: '训练营梯队人员详情页',
                            name: '训练营梯队人员详情页',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/team/details'),
                    },
                ],
                path: '/camp/team/index',
                meta: {
                    disable: false,
                    desc: '训练营梯队',
                    descEn: 'Camp Team',
                    key: 'camp-team',
                    name: '训练营梯队',
                    type: 'menu',
                    level: 1,
                    hidden: false,
                },
                component: () => import('@/views/camp/team/index'),
            },
            {
                children: [
                    {
                        children: [],
                        path: '/camp/injury/index',
                        meta: {
                            disable: false,
                            desc: '伤病列表',
                            name: '伤病列表',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/injury/index'),
                    },
                    {
                        children: [],
                        path: '/camp/injury/injury-detail',
                        meta: {
                            disable: false,
                            desc: '伤病详情',
                            name: '伤病详情',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/injury/injury-detail'),
                    },
                    {
                        children: [],
                        path: '/camp/injury/injury-add',
                        meta: {
                            disable: false,
                            desc: '伤病新增',
                            name: '伤病新增',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/injury/injury-add'),
                    },
                ],
                path: '/camp/injury/index',
                meta: {
                    disable: false,
                    desc: '训练营伤病',
                    descEn: 'Camp Injury',
                    key: 'camp-injury',
                    name: '训练营伤病',
                    type: 'menu',
                    level: 1,
                    hidden: false,
                },
                component: () => import('@/views/camp/injury/index'),
            },
            {
                children: [
                    {
                        children: [],
                        path: '/camp/video/edit',
                        meta: {
                            disable: false,
                            desc: '训练营视频-编辑',
                            key: '/camp/video/edit',
                            name: '训练营视频-编辑',
                            type: 'menu',
                            level: 0,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/video/edit'),
                    },
                    {
                        children: [],
                        path: '/camp/video/index',
                        meta: {
                            disable: false,
                            desc: '训练营视频-首页',
                            name: '训练营视频-首页',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/video/index'),
                    },
                ],
                path: '/camp/video/index',
                meta: {
                    disable: false,
                    desc: '训练营视频',
                    descEn: 'Camp Video',
                    key: 'camp-video',
                    name: '训练营视频',
                    type: 'menu',
                    level: 1,
                    hidden: false,
                },
                component: () => import('@/views/camp/video/index'),
            },
            {
                children: [
                    {
                        children: [
                            {
                                children: [
                                    {
                                        children: [],
                                        path: '/camp/report/player/list',
                                        meta: {
                                            disable: false,
                                            desc: '球员评估列表',
                                            name: '球员评估列表',
                                            type: 'menu',
                                            level: 4,
                                            hidden: true,
                                        },
                                        component: () => import('@/views/camp/report/player/list'),
                                    },
                                    {
                                        children: [],
                                        path: '/camp/report/player/detail',
                                        meta: {
                                            disable: false,
                                            desc: '球员评估详情',
                                            name: '球员评估详情',
                                            type: 'menu',
                                            level: 4,
                                            hidden: true,
                                        },
                                        component: () => import('@/views/camp/report/player/detail'),
                                    },
                                ],
                                img: 'https://acme-public.oss-cn-beijing.aliyuncs.com/shenzhen/files/7e19aa52-ab96-444c-821a-d168080b5c71',
                                path: '/camp/report/player/list',
                                meta: {
                                    disable: false,
                                    desc: '球员评估',
                                    descEn: 'Player Eval',
                                    name: '球员评估',
                                    type: 'menu',
                                    level: 3,
                                    hidden: false,
                                },
                                component: () => import('@/views/camp/report/player/list'),
                            },
                            {
                                children: [
                                    {
                                        children: [],
                                        path: '/camp/report/staff/list',
                                        meta: {
                                            disable: false,
                                            desc: '教练组评估列表',
                                            name: '教练组评估列表',
                                            type: 'menu',
                                            level: 4,
                                            hidden: true,
                                        },
                                        component: () => import('@/views/camp/report/staff/list'),
                                    },
                                    {
                                        children: [],
                                        path: '/camp/report/staff/detail',
                                        meta: {
                                            disable: false,
                                            desc: '教练组评估详情',
                                            name: '教练组评估详情',
                                            type: 'menu',
                                            level: 4,
                                            hidden: true,
                                        },
                                        component: () => import('@/views/camp/report/staff/detail'),
                                    },
                                ],
                                img: 'https://acme-public.oss-cn-beijing.aliyuncs.com/shenzhen/files/38eeacac-e0c9-4710-9c7b-fd79204de121',
                                path: '/camp/report/staff/list',
                                meta: {
                                    disable: false,
                                    desc: '教练组评估',
                                    descEn: 'Coach Group Eval',
                                    name: '教练组评估',
                                    type: 'menu',
                                    level: 3,
                                    hidden: false,
                                },
                                component: () => import('@/views/camp/report/staff/list'),
                            },
                            {
                                children: [
                                    {
                                        children: [],
                                        path: '/camp/report/physical-test/index',
                                        meta: {
                                            disable: false,
                                            desc: '体测报告首页',
                                            name: '体测报告首页',
                                            type: 'menu',
                                            level: 4,
                                            hidden: true,
                                        },
                                        component: () => import('@/views/camp/report/physical-test/index'),
                                    },
                                    {
                                        children: [],
                                        path: '/camp/report/physical-test/player-detail',
                                        meta: {
                                            disable: false,
                                            desc: '体测报告个人列表页',
                                            name: '体测报告个人列表页',
                                            type: 'menu',
                                            level: 4,
                                            hidden: true,
                                        },
                                        component: () => import('@/views/camp/report/physical-test/player-detail'),
                                    },
                                    {
                                        children: [],
                                        path: '/camp/report/physical-test/test-detail',
                                        meta: {
                                            disable: false,
                                            desc: '体测报告详情',
                                            name: '体测报告详情',
                                            type: 'menu',
                                            level: 4,
                                            hidden: true,
                                        },
                                        component: () => import('@/views/camp/report/physical-test/test-detail'),
                                    },
                                ],
                                img: 'https://acme-public.oss-cn-beijing.aliyuncs.com/shenzhen/files/1004ec1e-7f91-4bd5-82c9-7f8d93dd14d7',
                                path: '/camp/report/physical-test/index',
                                meta: {
                                    disable: false,
                                    desc: '体测报告',
                                    descEn: 'Physical',
                                    name: '体测报告',
                                    type: 'menu',
                                    level: 3,
                                    hidden: false,
                                },
                                component: () => import('@/views/camp/report/physical-test/index'),
                            },
                        ],
                        path: '/eavl',
                        meta: {
                            disable: false,
                            desc: '评估分析',
                            descEn: 'Assessment Analysis',
                            key: '',
                            name: '评估分析',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/eavl'),
                    },
                    {
                        children: [
                            {
                                children: [],
                                img: 'https://acme-public.oss-cn-beijing.aliyuncs.com/shenzhen/files/7d244db9-3c35-45d1-9d2a-52f8c9573724',
                                path: '/camp/report/injury-report/index',
                                meta: {
                                    disable: false,
                                    desc: '当日伤病报告',
                                    descEn: 'Daily Injury Reports',
                                    name: '当日伤病报告',
                                    type: 'menu',
                                    level: 3,
                                    hidden: false,
                                },
                                component: () => import('@/views/camp/report/injury-report/index'),
                            },
                            {
                                children: [
                                    {
                                        children: [],
                                        path: '/camp/report/player-video/index',
                                        meta: {
                                            disable: false,
                                            desc: '球员视频统计列表',
                                            name: '球员视频统计列表',
                                            type: 'menu',
                                            level: 4,
                                            hidden: true,
                                        },
                                        component: () => import('@/views/camp/report/player-video/index'),
                                    },
                                    {
                                        children: [],
                                        path: '/camp/report/player-video/detail',
                                        meta: {
                                            disable: false,
                                            desc: '球员视频统计详情',
                                            name: '球员视频统计详情',
                                            type: 'menu',
                                            level: 4,
                                            hidden: true,
                                        },
                                        component: () => import('@/views/camp/report/player-video/detail'),
                                    },
                                ],
                                img: 'https://acme-public.oss-cn-beijing.aliyuncs.com/shenzhen/files/e3a74b8d-a2f9-4edf-9e0d-4f1b435ed821',
                                path: '/camp/report/player-video/index',
                                meta: {
                                    disable: false,
                                    desc: '球员视频分析',
                                    descEn: 'Players Videos Analysis',
                                    name: '球员视频分析',
                                    type: 'menu',
                                    level: 3,
                                    hidden: false,
                                },
                                component: () => import('@/views/camp/report/player-video/index'),
                            },
                        ],
                        path: '/report-child',
                        meta: {
                            disable: false,
                            desc: '统计报告',
                            descEn: 'Accounting Report',
                            name: '统计报告',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/report-child'),
                    },
                    {
                        children: [
                            {
                                children: [],
                                img: 'https://acme-public.oss-cn-beijing.aliyuncs.com/shenzhen/files/9e80cb8d-7c1a-4534-addf-909de6e966a4',
                                path: '/camp/report/run-report/opening-camp',
                                meta: {
                                    disable: false,
                                    desc: '开营通知',
                                    descEn: 'Opening Notification',
                                    name: '开营通知',
                                    type: 'menu',
                                    level: 3,
                                    hidden: false,
                                },
                                component: () => import('@/views/camp/report/run-report/opening-camp'),
                            },
                            {
                                children: [],
                                img: 'https://acme-public.oss-cn-beijing.aliyuncs.com/shenzhen/files/107d0fbc-b269-4285-a852-d1defbb05b20',
                                path: '/camp/report/run-report/final-report',
                                meta: {
                                    disable: false,
                                    desc: '总结报告',
                                    descEn: 'Final Report',
                                    name: '总结报告',
                                    type: 'menu',
                                    level: 3,
                                    hidden: false,
                                },
                                component: () => import('@/views/camp/report/run-report/final-report'),
                            },
                        ],
                        path: '/run-report',
                        meta: {
                            disable: false,
                            desc: '运营报告',
                            descEn: 'Operation Report',
                            name: '运营报告',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/run-report'),
                    },
                    {
                        children: [
                            {
                                children: [
                                    {
                                        children: [],
                                        path: '/camp/report/work-logs/index',
                                        meta: {
                                            disable: false,
                                            desc: '工作日志列表',
                                            descEn: '工作日志列表',
                                            name: '工作日志列表',
                                            type: 'menu',
                                            level: 4,
                                            hidden: true,
                                        },
                                        component: () => import('@/views/camp/report/work-logs/index'),
                                    },
                                    {
                                        children: [],
                                        path: '/camp/report/work-logs/detail',
                                        meta: {
                                            disable: false,
                                            desc: '工作日志详情',
                                            descEn: '工作日志详情',
                                            name: '工作日志详情',
                                            type: 'menu',
                                            level: 4,
                                            hidden: true,
                                        },
                                        component: () => import('@/views/camp/report/work-logs/detail'),
                                    },
                                ],
                                img: 'https://acme-public.oss-cn-beijing.aliyuncs.com/shenzhen/files/c7497a41-b834-46cd-af4f-f215c7bd15ac',
                                path: '/camp/report/work-logs/index',
                                meta: {
                                    disable: false,
                                    desc: '工作日志',
                                    descEn: 'Daily Notes',
                                    name: '工作日志',
                                    type: 'menu',
                                    level: 3,
                                    hidden: false,
                                },
                                component: () => import('@/views/camp/report/work-logs/index'),
                            },
                        ],
                        path: '/week-summary',
                        meta: {
                            disable: false,
                            desc: '周总结',
                            descEn: 'Week Summary',
                            name: '周总结',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/week-summary'),
                    },
                    {
                        children: [],
                        path: '/camp/report/index',
                        meta: {
                            disable: false,
                            desc: '训练营报告主页',
                            name: '训练营报告主页',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/report/index'),
                    },
                ],
                path: '/camp/report/index',
                meta: {
                    disable: false,
                    desc: '训练营报告',
                    descEn: 'Camp Report',
                    key: 'camp-report',
                    name: '训练营报告',
                    type: 'menu',
                    level: 1,
                    hidden: false,
                },
                component: () => import('@/views/camp/report/index'),
            },
            {
                children: [
                    {
                        children: [
                            {
                                children: [],
                                path: '/camp/mgmt/template/details',
                                meta: {
                                    disable: false,
                                    desc: '训练营管理-模板管理-详情',
                                    descEn: 'Camp Mgmt Tem Details',
                                    key: 'camp-mgmt-tem-details',
                                    name: '训练营管理-模板管理-详情',
                                    type: 'menu',
                                    level: 3,
                                    hidden: true,
                                },
                                component: () => import('@/views/camp/mgmt/template/details'),
                            },
                            {
                                children: [],
                                path: '/camp/mgmt/template/detailsAddEdit',
                                meta: {
                                    disable: false,
                                    desc: '训练营管理-模板管理-添加编辑详情',
                                    descEn: 'Camp Mgmt Tem Details AE',
                                    key: 'camp-mgmt-tem-details-AE',
                                    name: '训练营管理-模板管理-添加编辑详情',
                                    type: 'menu',
                                    level: 3,
                                    hidden: true,
                                },
                                component: () => import('@/views/camp/mgmt/template/detailsAddEdit'),
                            },
                            {
                                children: [],
                                path: '/camp/mgmt/template/index',
                                meta: {
                                    disable: false,
                                    desc: '训练营管理-模板管理-首页',
                                    name: '训练营管理-模板管理-首页',
                                    type: 'menu',
                                    level: 3,
                                    hidden: true,
                                },
                                component: () => import('@/views/camp/mgmt/template/index'),
                            },
                            {
                                children: [],
                                path: '/camp/mgmt/template/detailsAddEdit/schedule',
                                meta: {
                                    disable: false,
                                    desc: '添加编辑日程',
                                    name: '添加编辑日程',
                                    type: 'menu',
                                    level: 3,
                                    hidden: true,
                                },
                                component: () => import('@/views/camp/mgmt/template/detailsAddEdit/schedule'),
                            },
                            {
                                children: [],
                                path: '/camp/mgmt/template/details/schedule',
                                meta: {
                                    disable: false,
                                    desc: '日程详情',
                                    name: '日程详情',
                                    type: 'menu',
                                    level: 3,
                                    hidden: true,
                                },
                                component: () => import('@/views/camp/mgmt/template/details/schedule'),
                            },
                        ],
                        path: '/camp/mgmt/template/index',
                        meta: {
                            disable: false,
                            desc: '训练营管理-模板管理',
                            descEn: 'Camp Mgmt Tem ',
                            key: 'camp-mgmt-tem',
                            name: '训练营管理-模板管理',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/mgmt/template/index'),
                    },
                    {
                        children: [],
                        path: '/camp/mgmt/index',
                        meta: {
                            disable: false,
                            desc: '训练营管理-首页',
                            descEn: '',
                            name: '训练营管理-首页',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/mgmt/index'),
                    },
                    {
                        children: [],
                        path: '/camp/mgmt/details',
                        meta: {
                            disable: false,
                            desc: '训练营管理-详情',
                            name: '训练营管理-详情',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/mgmt/details'),
                    },
                    {
                        children: [],
                        path: '/camp/mgmt/details/scheduleAddEdit',
                        meta: {
                            disable: false,
                            desc: '训练营管理-编辑添加日程',
                            name: '训练营管理-编辑添加日程',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/mgmt/details/scheduleAddEdit'),
                    },
                    {
                        children: [],
                        path: '/camp/mgmt/details/schedule',
                        meta: {
                            disable: false,
                            desc: '训练营管理-日程',
                            name: '训练营管理-日程',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/mgmt/details/schedule'),
                    },
                    {
                        children: [],
                        path: '/camp/mgmt/importPlan/index',
                        meta: {
                            disable: false,
                            desc: '训练营管理-导入计划',
                            name: '训练营管理-导入计划',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/mgmt/importPlan/index'),
                    },
                    {
                        children: [],
                        path: '/camp/mgmt/importPlan/detail',
                        meta: {
                            disable: false,
                            desc: '训练营管理-导入计划详情',
                            name: '训练营管理-导入计划详情',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/mgmt/importPlan/detail'),
                    },
                    {
                        children: [],
                        path: '/camp/mgmt/importPlan/setting',
                        meta: {
                            disable: false,
                            desc: '训练营管理-导入计划设置',
                            name: '训练营管理-导入计划设置',
                            type: 'menu',
                            level: 2,
                            hidden: true,
                        },
                        component: () => import('@/views/camp/mgmt/importPlan/setting'),
                    },
                ],
                path: '/camp/mgmt/index',
                meta: {
                    disable: false,
                    desc: '训练营管理',
                    descEn: 'Camp Mgmt',
                    key: 'camp-mgmt',
                    name: '训练营管理',
                    type: 'menu',
                    level: 1,
                    hidden: false,
                },
                component: () => import('@/views/camp/mgmt/index'),
            },
        ],
    },
];
